title: "Hack in Brasil — Comunidade de Segurança da Informação"
description: "Comunidade brasileira de cibersegurança"
lang: pt-BR
timezone: America/Sao_Paulo
markdown: kramdown
collections:
  blog:
    output: true
    permalink: /blog/:name/
  sponsors:
    output: true
    permalink: /patrocinadores/:name/
  speakers:
    output: true
    permalink: /palestrantes/:name/
  supporters:
    output: true
    permalink: /apoiadores/:name/
plugins: []
exclude:
  - README.md
