title: "Hack in Brasil — Comunidade de Segurança da Informação"
description: "Comunidade brasileira de cibersegurança"
url: "https://hackinbrasil.com.br"
lang: pt-BR
timezone: America/Sao_Paulo
markdown: kramdown
logo: /assets/images/hackinbrasil.png
twitter:
  card: summary_large_image
social:
  name: Hack in Brasil
  links:
    - https://chat.whatsapp.com/D4vKksmiQ53JpVMih0PF4b
collections:
  blog:
    output: true
    permalink: /blog/:name/
  sponsors:
    output: true
    permalink: /patrocinadores/:name/
  speakers:
    output: true
    permalink: /palestrantes/:name/
  supporters:
    output: true
    permalink: /apoiadores/:name/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/hackinbrasil.png

exclude:
  - README.md
